language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

env:
  global:
    - CIBW_TEST_REQUIRES=pytest
    - CIBW_TEST_COMMAND="pytest"
    - TWINE_USERNAME=nvictus
    # Note: TWINE_PASSWORD is set in Travis settings

script:
  - $PIP install cibuildwheel
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m pip install twine
      python -m twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
    fi
