language: python
notifications:
  email: false


# The matrix expands to 3 builds: OSX and linux to build wheels
# and py36 and py37 for general testing
# For more information about building wheels, see:
# https://pythonwheels.com/
# https://github.com/joerick/cibuildwheel
# https://malramsay.com/post/perils_of_packaging/
matrix:
  include:
    - os: linux
      sudo: required
      services: docker
      python: '3.6'
      env:
        - CIBW_BEFORE_BUILD='yum install -y gcc make zlib-devel openssl-devel libpng-devel && pip install numpy cython'

    - os: linux
      dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required
      services: docker
      python: '3.7'
      env:
        - CIBW_BEFORE_BUILD='yum install -y gcc make zlib-devel openssl-devel libpng-devel && pip install numpy cython'

    - os: linux
      dist: xenial    # required for Python 3.8 (travis-ci/travis-ci#9069)
      sudo: required
      services: docker
      python: '3.8'
        - CIBW_BEFORE_BUILD='yum install -y gcc make zlib-devel openssl-devel libpng-devel && pip install numpy cython'

    - os: osx
      language: generic
      env:
        - C_INCLUDE_PATH="/usr/local/include/libpng:/usr/local/opt/openssl/include:$C_INCLUDE_PATH"


# The last 2 vars are set to assure Python 3 is used on OS X (mac)
env:
  global:
    - CIBW_SKIP="cp27-* cp33-* cp34-*
    - CIBW_BUILD_VERBOSITY=3
    - CIBW_TEST_REQUIRES=""
    - CIBW_TEST_COMMAND='python -c "import bbi"'
    - PIP=pip3
    - PYTHON=python3


# If OS X - install Python 3 as python3.
# Print the python version, install general requirements and linting
before_install:
  # - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then
  #   brew update;
  #   fi
  - if [ "${TRAVIS_OS_NAME:-}" -ne "osx" ]; then
    sudo apt install libpython3.6-dev;
    fi
  - $PYTHON --version
  # - $PIP install -r requirements.txt
  # - $PIP install pep8>=1.7.1
  # - $PIP install flake8>=3.5.0


script:
  - $PIP install cibuildwheel
  - $PYTHON -m cibuildwheel --output-dir wheelhouse
  - ls -asl wheelhouse/
  # - |
  #   if [[ $TRAVIS_TAG ]]; then
  #     python -m pip install twine
  #     python -m twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
  #   fi
