language: python
notifications:
  email: false

matrix:
  include:
    - sudo: required
      services:
        - docker

    - os: osx
      language: generic

script:
  - mkdir -p wheels
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
      docker create --name cibw -i quay.io/pypa/manylinux2010_x86_64;
      docker cp $(pwd) cibw:/project;
      docker start -i -a cibw < ci/buildwheel_manylinux.sh;
      docker cp cibw:/tmp/wheelhouse/. wheels;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then 
      bash ci/buildwheel_macosx.sh;
      mv /tmp/wheelhouse/*.whl wheels;
    fi
  - ls -asl wheels
