language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: 
        - PIP=pip
        - CIBW_SKIP='cp27-*'
        - CIBW_BEFORE_BUILD="yum install -y gcc make zlib-devel openssl-devel libpng-devel"
    - os: osx
      language: generic
      env: 
        - PIP=pip2
        - CIBW_SKIP='cp27-*'

env:
  global:
    - CIBW_TEST_REQUIRES=pytest
    - CIBW_TEST_COMMAND="pytest"
    - TWINE_USERNAME=nvictus
    # Note: TWINE_PASSWORD is set in Travis settings

script:
  - $PIP install cibuildwheel
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m pip install twine
      python -m twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
    fi
